### ISSUE TITLE
Postpone surface creation to Resumed event

### ISSUE THREAD

**Issue by happy-turtle** [sotrh/wgpu-on-android#1]
Coming from your tutorial learn-wgpu I saw this repo. Are you still interested in fixing it? I've tried running wgpu cross platform for the past months and got a basic setup working on desktop, android and wasm. What I've found is that on Android the surface is not valid until the window `Resumed` event is thrown. So we have to postpone surface creation until receiving this event, see [here](https://github.com/gfx-rs/wgpu/wiki/Running-on-Android). That fact was a bit hidden in issues to winit and wgpu e.g. [here](https://github.com/gfx-rs/wgpu/issues/1757#issuecomment-892042298).
I got working repositories for [cross compilation](https://github.com/happy-turtle/crusty-renderer) or only for [android](https://github.com/happy-turtle/wgpu-android). If it helps I wouldn't mind contributing with a pull request here or at learn-wgpu.

**Comment by sotrh** [comment]
This repo was meant as a test for my learn-wgpu repo. I haven't touched it in awhile, so the code is not using the latest version of wgpu. I'll be honest I'm not sure what to do with it.

I should probably archive this repo as address mobile support on learn wgpu itself. You're welcome to fork this and fix it, but it would probably be easier just to create your own example repo.

**Comment by happy-turtle** [comment]
Sounds good, if I can help at learn-wgpu with this, please let me know. I got a working example for myself already: [wgpu-android](https://github.com/happy-turtle/wgpu-android). I was mostly interested in bringing those findings to the place where most people look when coming to wgpu the first time,  that is learn-wgpu.
